module:
  ace_editor: 0
  action: 0
  address: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  allowed_formats: 0
  asset_injector: 0
  auto_entitylabel: 0
  automated_cron: 0
  backup_migrate: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_class: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  ckeditor_templates: 0
  color: 0
  color_field: 0
  config: 0
  config_filter: 0
  config_partial_export: 0
  config_split: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  crop: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  curator: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_entity_updates: 0
  dropzonejs: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  fences: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  filter: 0
  focal_point: 0
  fontawesome: 0
  fontawesome_menu_icons: 0
  gnode: 0
  google_analytics: 0
  group: 0
  groupmenu: 0
  groupmenu_block: 0
  gtranslate: 0
  help: 0
  html_title: 0
  image: 0
  imagemagick: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  kwall_alert_system: 0
  kwall_map: 0
  kwall_share_bar: 0
  language: 0
  libraries: 0
  link: 0
  link_attributes: 0
  link_class: 0
  linkit: 0
  markup: 0
  masquerade: 0
  media: 0
  media_bulk_upload: 0
  media_entity_file_replace: 0
  media_library: 0
  menu_block: 0
  menu_ui: 0
  metatag: 0
  metatag_app_links: 0
  metatag_facebook: 0
  metatag_favicons: 0
  metatag_google_cse: 0
  metatag_google_plus: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  metatag_views: 0
  migrate: 0
  migrate_drupal: 0
  module_filter: 0
  name: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quick_node_clone: 0
  quicklink: 0
  rdf: 0
  recaptcha: 0
  redirect: 0
  rest: 0
  search_api: 0
  search_api_db: 0
  search_api_solr: 0
  serialization: 0
  shortcut: 0
  simplesamlphp_auth: 0
  smtp: 0
  sophron: 0
  soundcloudfield: 0
  switch_page_theme: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_field_value: 0
  twig_link_attributes: 0
  twig_tweak: 0
  twig_vardumper: 0
  ultimate_cron: 0
  update: 0
  user: 0
  variationcache: 0
  verf: 0
  views_bulk_operations: 0
  views_templates: 0
  views_ui: 0
  viewsreference: 0
  webform: 0
  webform_access: 0
  webform_node: 0
  webform_scheduled_email: 0
  webform_submission_log: 0
  webform_templates: 0
  webform_ui: 0
  workflows: 0
  wysiwyg_template: 0
  wysiwyg_template_core: 0
  xmlsitemap_engines: 0
  menu_link_content: 1
  pathauto: 1
  xmlsitemap: 1
  externalauth: 10
  views: 10
  paragraphs: 11
  linked_field: 100
  custom_module: 1000
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  zurb_foundation: 0
  santa_cruz: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
